For teacher
SofiaPirogova/goit-markup-hw-03 pull request #1
Opened 2020-12-25 15:16 UTC by SofiaPirogova

Очень надеюсь, что в этот раз ничего не проморгала:)))

2020-12-26 11:32 UTC, magom001 requested changes

2020-12-26 11:32 UTC, magom001 commented on CSS/style.css
> +*::before,
это зачем?

2020-12-26 11:32 UTC, magom001 commented on CSS/style.css
> +  border-bottom: 1px solid #ececec;
почему цвета не в переменных?

2020-12-26 11:32 UTC, magom001 commented on CSS/style.css
> +.header {
у тебя в хэдере элементы не выровнены по вертикали (посмотри на страницу)

2020-12-26 11:32 UTC, magom001 commented on CSS/style.css
> +  border: 1px solid #eeeeee;
цвет не в переменной

2020-12-26 11:32 UTC, magom001 commented on CSS/style.css
> +.gallery-back:nth-last-child(-n + 3) {
https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

2020-12-26 11:32 UTC, magom001 commented on CSS/style.css
> +  color: rgba(255, 255, 255, 0.6);
цвет не в переменной

2020-12-26 12:55 UTC, SofiaPirogova commented on CSS/style.css
> +*::before,
так делал Саша Репета во всех видео. Это помогает делать так, чтобы ну точно размеры бокса не увеличивались нигде ни при рамке, ни при чем. Без этого (я писала в описании реквеста) не хватало настроек нормалайза(модерн нормалайз тоже проверяла) и карточки вместо прописанных 370 становились 372 с бордером. padding-inline-start я сама добавила туда же - это быстро решило проблему хреновых отступов, чтобы не переделывать это в большинстве документа.

2020-12-26 12:58 UTC, SofiaPirogova commented on CSS/style.css
> +  border-bottom: 1px solid #ececec;
насколько я помню мы только повторяющиеся цвета договаривались в переменные ставить. Но я могу ошибаться, переделаю в любом случае, а потом уточните для меня пожалуйста.

2020-12-26 13:08 UTC, SofiaPirogova commented on CSS/style.css
> +.gallery-back:nth-last-child(-n + 3) {
сделала формулу ровно по конспекту (но меня смущает, что может это не верный подход  - но тогда мне нужно объяснить, потому что я не понимаю, единственное как убрать марджин у трех нижних элементов я вижу только такой путь, либо сокращать падинг секции  - это наверно попроще, но я хотела заморочиться) Ниже выдержка из конспекта плюс ссылка с вашего же ресурса, но именно по ласт чайлд [https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child](url)
"До N-го элемента#
Чтобы выбрать несколько последних элементов в коллекции, используется формула -n + b, где b это количество выбираемых элементов. Например, при b = 3 будут выбраны только последние три элемента.

Селектор nth-child
.list-item:nth-last-child(-n + 3) {
  background-color: orange; "

2020-12-26 13:45 UTC, magom001 commented on CSS/style.css
> +*::before,
я про *::before, *::after. Ты понимаешь, зачем это написано?

2020-12-26 13:45 UTC, magom001 commented on CSS/style.css
> +  border-bottom: 1px solid #ececec;
нет, мы договаривались всю палитру держать в переменных

2020-12-26 13:50 UTC, magom001 commented on CSS/style.css
> +.gallery-back:nth-last-child(-n + 3) {
Вот как все ломается: у тебя будет не число кратное 3 (как сейчас), а, например, 8. Тогда твой стили применится к последним 3: 2-м в последнем ряду и 3-му элементу во втором ряду. Я могу тебе дать свое решение, но какой в этом смысл? Найди свой способ.

2020-12-26 14:48 UTC, SofiaPirogova commented on CSS/style.css
> +*::before,
честно говоря нет,я спрашивала на занятии, но мой вопрос пропустили. У Саши стоит  - просто тупо копирую. Читала конкретно про эти штуки, но так и не поняла зачем они тут. Хотела поднять этот вопрос на следующей с вами всеобщей встречи, если не смогу сама разобраться.  Саша в видео говорил что это это для встраиваемых хреней устаревших тоже, но, честно говоря, я пока не совсем вдуплила.

2020-12-26 14:52 UTC, SofiaPirogova commented on CSS/style.css
> +.gallery-back:nth-last-child(-n + 3) {
да я об этом думала, с другой стороны, если взять 8 или 7 (не кратно трем) - то не будет нижнего отступа у крайнего(крайних) справа в предыдущей строчке - но под ним нет картинки - значит по факту на визуал влиять не будет. Но я проверю эту теорию на всякий пожарный.

2020-12-26 18:02 UTC, SofiaPirogova commented on CSS/style.css
> +.gallery-back:nth-last-child(-n + 3) {
и если я уберу у верхних трех элементов марджины топ- это тоже не вариант- потому что дизайнер может добавлять фото и по другому. Хотя врядли. могу убрать тогда верхние марджины. или это не вариант тоже?

2020-12-26 19:08 UTC, magom001 commented on CSS/style.css
> +*::before,
вот за "просто тупо копирую" двойка тебе!

2020-12-26 19:10 UTC, magom001 commented on CSS/style.css
> +.gallery-back:nth-last-child(-n + 3) {
задайся вопросом, нужно ли тебе вообще убирать отступ у нижних элементов

2020-12-27 11:13 UTC, SofiaPirogova commented on CSS/style.css
> +*::before,
попрошу воздержаться от оценок - это неуместно и НИКАК не помогает.

2020-12-28 13:40 UTC, magom001 commented on CSS/style.css
>  .gallery-back {
обрати внимание, что у тебя картинка заезжает за край коробки

2020-12-28 13:42 UTC, magom001 commented on CSS/style.css
> +.button:focus {
обрати внимание, что на макетах у кнопки есть тень

2020-12-28 13:43 UTC, magom001 approved these changes
Поправь по замечаниям и сойдет.

2021-01-08 11:57 UTC, magom001 approved these changes

2021-01-08 11:57 UTC, magom001 commented on CSS/style.css
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 1px rgba(0, 0, 0, 0.14),
дизайнер упоролся

2021-01-08 11:57 UTC, magom001 commented on CSS/style.css
> +  border-bottom: 1px solid var(--border-gallery);
hint: можно просто сделать `border: ...`, а следом `border-top: none`

2021-01-15 17:27 UTC, merged